export const predictTaskName ={
    'threeMonthDeath': '三月内死亡',
    'threeMonthRevascular': '三月内血运重建',
    'threeMonthRenalDisease': '三月内肾病再入院',
    'threeMonthOther': '三月内其它原因再入院',
    'threeMonthNYHAClass1': '三月内NYHA 1级再入院',
    'threeMonthNYHAClass2': '三月内NYHA 2级再入院',
    'threeMonthNYHAClass3': '三月内NYHA 3级再入院',
    'threeMonthNYHAClass4': '三月内NYHA 4级再入院',
    'threeMonthLungDisease': '三月内肺病',
    'threeMonthCancer': '三月内癌症再入院',
    'oneYearCancer': '一年内癌症再入院',
    'oneYearDeath': '一年内死亡',
    'oneYearRevascular': '一年内血运重建',
    'oneYearRenalDisease': '一年内肾病再入院',
    'oneYearOther': '一年内其它原因再入院',
    'oneYearNYHAClass1': '一年内NYHA 1级再入院',
    'oneYearNYHAClass2': '一年内NYHA 2级再入院',
    'oneYearNYHAClass3': '一年内NYHA 3级再入院',
    'oneYearNYHAClass4': '一年内NYHA 4级再入院',
    'oneYearLungDisease': '一年内肺病',
    'oneYearCancer': '一年内癌症再入院',
};